### ISSUE TITLE
boilerplate

### ISSUE THREAD

**Issue by holyxiaoxin** [ooade/awesome-apollo-graphql#1]
Please add this in: 

https://github.com/MacKentoch/react-redux-graphql-apollo-bootstrap-webpack-starter

**Comment by ooade** [comment]
@MacKentoch do you mind giving your repo a better description? Check this out: https://github.com/sindresorhus/awesome/pull/988#issuecomment-316099422

**Comment by MacKentoch** [comment]
Hi @ooade 

Sure.

I tried to respect the conciseness of the description.
Is that ok: #2 ?

**Comment by ooade** [comment]
It's okay @MacKentoch 
Cheers :+1:
